### PR TITLE
fix(md-enhance): the relative image/link path error in the include markdown file.

### LINKED ISSUE #2142: [Bug] md-enhance include directive can not process related image path to display
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope/packages/md-enhance

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

The `include` directive can not process the related image path correctly.

The image can be only viewed in the original document.

* file: ./guide/get-started/intro.md

```md
Some pics to includes

![img](./apic.jpg)

## Other not include

```

* file: ./another-file,md

```md
@include(./guide/get-started/intro.md{1-3})
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snowyu**
Fixed #2142

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Thanks for the great work, I will review it when I have time.

File: packages/md-enhance/src/node/markdown-it/include.ts [hunk 1]
```diff
@@ -51,10 +54,21 @@ export const handleInclude = (
...
     .split("\n")
-    .slice(lineStart ? lineStart - 1 : lineStart, lineEnd)
+    .slice(lineStart ? lineStart - 1 : lineStart, lineEnd);
+
+  if (resolvedPath && realPath.endsWith(".md")) {
+    const dirName = path.dirname(realPath);
+    result.unshift(`@include-push(${dirName})`);
+    result.push("@include-pop()");
+  }
+  // if (realPath.endsWith("includeLink.md")) {
```
Comment (Mister-Hope) [inline packages/md-enhance/src/node/markdown-it/include.ts:67]: comment here

File: packages/md-enhance/src/node/markdown-it/include.ts [hunk 2]
```diff
@@ -118,14 +133,137 @@ export const createIncludeCoreRule =
...
+  if (resolveImagePath || resolveLinkPath) {
+    md.block.ruler.before(
+      "table",
+      "md_includePush",
+      includePushRule,
+      {alt: [ 'paragraph', 'reference', 'blockquote', 'list' ]},
+    );
+    md.block.ruler.before(
+      "table",
+      "md_includePop",
```
Comment (Mister-Hope) [inline packages/md-enhance/src/node/markdown-it/include.ts:223]: md_include_push could be better

File: packages/md-enhance/src/node/markdown-it/include.ts [hunk 3]
```diff
@@ -118,14 +130,137 @@ export const createIncludeCoreRule =
...
+  let url = token.attrs?.[aIndex][1];
+  if (url?.startsWith('.') && filePath) {
+    const len = Array.isArray(includedPaths) && includedPaths.length;
+    if (len) {
+      const includeDir = path.relative(path.dirname(filePath), includedPaths[len-1]);
+      url = "." + path.sep + path.join(includeDir, url);
+      token.attrs![aIndex][1] = url;
+    }
+  }
+}
```
Comment (Mister-Hope) [inline packages/md-enhance/src/node/markdown-it/include.ts:198]:
```suggestion
}

```

File: packages/md-enhance/src/node/markdown-it/include.ts [hunk 4]
```diff
@@ -118,14 +130,137 @@ export const createIncludeCoreRule =
...
+      token.map   = [ startLine, state.line ];
+      token.markup = 'incPop';
+    } else {
+      result = false;
+    }
+  }
+  return result;
+}
+
+function resolveRelatedLink(attr: string, token: Token, filePath: string, includedPaths?: string[]) {
```
Comment (Mister-Hope) [inline packages/md-enhance/src/node/markdown-it/include.ts:187]:
```suggestion
constresolveRelatedLink = (attr: string, token: Token, filePath: string, includedPaths?: string[]):void => {
```

File: packages/md-enhance/src/shared/include.ts [hunk 5]
```diff
@@ -16,4 +16,20 @@ export interface IncludeOptions {
    * @default false
    */
   deep?: boolean;
+  /**
```
Comment (Mister-Hope) [inline packages/md-enhance/src/shared/include.ts:19]:
```suggestion

    /**
```

File: packages/md-enhance/src/shared/include.ts [hunk 6]
```diff
@@ -16,4 +16,20 @@ export interface IncludeOptions {
...
+   * Whether resolve the image related path in the included markdown file
+   *
+   * 是否解析包含的 markdown 文件的里的相对图像路径
+   *
+   * @default true
+   */
+  resolveImagePath?: boolean;
+  /**
```
Comment (Mister-Hope) [inline packages/md-enhance/src/shared/include.ts:27]:
```suggestion

  /**
```

File: packages/md-enhance/src/node/markdown-it/include.ts [hunk 7]
```diff
@@ -118,14 +130,138 @@ export const createIncludeCoreRule =
...
+  if (url?.startsWith('.') && filePath) {
+    const len = Array.isArray(includedPaths) && includedPaths.length;
+    if (len) {
+      const includeDir = path.relative(path.dirname(filePath), includedPaths[len-1]);
+      url = "." + path.sep + path.join(includeDir, url);
+      token.attrs![aIndex][1] = url;
+    }
+  }
+};
+
```
Comment (Mister-Hope) [inline packages/md-enhance/src/node/markdown-it/include.ts:199]:
```suggestion
const resolveRelatedLink = (attr: string, token: Token, filePath: string, includedPaths?: string[]):void => {
  let url = token.attrs?.[token.attrIndex(attr)][1];

  if (url?.startsWith('.') && filePath && Array.isArray(includedPaths)) {
    const { length }= includedPaths;

    if (length ) {
      const includeDir = path.relative(path.dirname(filePath), includedPaths[length-1]);

      url = `.${path.sep}${path.join(includeDir, url)}`;
      token.attrs![aIndex][1] = url;
    }
  }
};

```

File: packages/md-enhance/src/node/markdown-it/include.ts [hunk 8]
```diff
@@ -118,14 +130,138 @@ export const createIncludeCoreRule =
...
+    md.renderer.rules["vth_inc_push"] = function (tokens, idx, _options, env, _self) {
+      const token = tokens[idx];
+      const includedPaths = env.includedPaths || (env.includedPaths = []);
+      includedPaths.push(token.info);
+      return "";
+    };
+
+    md.renderer.rules["vth_inc_pop"] = function (_tokens, _idx, _options, env, _self) {
+      // const token = tokens[idx];
```
Comment (Mister-Hope) [inline packages/md-enhance/src/node/markdown-it/include.ts:234]:
```suggestion
```

File: packages/md-enhance/src/node/markdown-it/include.ts [hunk 9]
```diff
@@ -118,14 +130,138 @@ export const createIncludeCoreRule =
...
+      {alt: [ 'paragraph', 'reference', 'blockquote', 'list' ]},
+    );
+    md.block.ruler.before(
+      "table",
+      "md_include_pop",
+      includePopRule,
+      {alt: [ 'paragraph', 'reference', 'blockquote', 'list' ]},
+    );
+
+    md.renderer.rules["vth_inc_push"] = function (tokens, idx, _options, env, _self) {
```
Comment (Mister-Hope) [inline packages/md-enhance/src/node/markdown-it/include.ts:226]: What does `vth_inc_push` mean here

File: packages/md-enhance/src/node/markdown-it/include.ts [hunk 10]
```diff
@@ -51,10 +54,18 @@ export const handleInclude = (
...
   // return content
-  return fileContent
+  const result = fileContent
     .replace(NEWLINES_RE, "\n")
     .split("\n")
-    .slice(lineStart ? lineStart - 1 : lineStart, lineEnd)
+    .slice(lineStart ? lineStart - 1 : lineStart, lineEnd);
+
+  if (resolvedPath && realPath.endsWith(".md")) {
+    const dirName = path.dirname(realPath);
```
Comment (Mister-Hope) [inline packages/md-enhance/src/node/markdown-it/include.ts:63]:
```suggestion
    const dirName = path.dirname(realPath);

```
